#!/bin/bash
# Script to help push this repository to GitHub

echo "=========================================="
echo "GitHub Repository Setup"
echo "=========================================="
echo ""
echo "Your local git repository is ready!"
echo "Commit: $(git log --oneline -1)"
echo ""
echo "To upload to GitHub, follow these steps:"
echo ""
echo "1. Go to https://github.com/new"
echo "   - Repository name: CTA_project_ChiEAC"
echo "   - Description: Chicago Transit Data Analysis Project"
echo "   - Choose Public or Private"
echo "   - DO NOT initialize with README (we already have one)"
echo "   - Click 'Create repository'"
echo ""
echo "2. After creating the repository, GitHub will show you commands."
echo "   Run these commands (replace YOUR_USERNAME with your GitHub username):"
echo ""
echo "   git remote add origin https://github.com/YOUR_USERNAME/CTA_project_ChiEAC.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo ""
echo "=========================================="
echo "Alternative: If you want to use SSH instead of HTTPS:"
echo "   git remote add origin git@github.com:YOUR_USERNAME/CTA_project_ChiEAC.git"
echo "   git branch -M main"
echo "   git push -u origin main"
echo "=========================================="

